'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { 
  Brain, 
  Search, 
  History, 
  Clock, 
  Layers, 
  Plus, 
  TrendingUp,
  AlertCircle
} from 'lucide-react';
import { api, Memory } from '@/lib/api';

const MOCK_MEMORIES: Memory[] = [
  { id: 203, campaign_id: 3, memory_text: "Campaign ID 3 for ClearSkinCo (Skincare industry). Style: Before/After UGC. Audience: Women 20-35. Performance: CTR 5.2%, Conversion Rate 3.5%. Client Feedback/Learnings: Before/After UGC transition increased retention and drove massive purchases.", created_at: new Date().toISOString(), brand: "ClearSkinCo", industry: "Skincare", style: "Before/After UGC" },
  { id: 202, campaign_id: 2, memory_text: "Campaign ID 2 for RadiantSkin (Skincare industry). Style: Founder Video. Audience: Women 20-35. Performance: CTR 2.1%, Conversion Rate 0.8%. Client Feedback/Learnings: Founder story video underperformed. Users dropped off quickly.", created_at: new Date(Date.now() - 86400000).toISOString(), brand: "RadiantSkin", industry: "Skincare", style: "Founder Video" },
  { id: 201, campaign_id: 1, memory_text: "Campaign ID 1 for GlowSerums (Skincare industry). Style: UGC. Audience: Women 20-35. Performance: CTR 4.8%, Conversion Rate 2.1%. Client Feedback/Learnings: UGC style was highly engaging and generated high CTR.", created_at: new Date(Date.now() - 172800000).toISOString(), brand: "GlowSerums", industry: "Skincare", style: "UGC" }
];

export default function MemoryPage() {
  const [memories, setMemories] = useState<Memory[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [isDemoMode, setIsDemoMode] = useState(false);

  useEffect(() => {
    async function loadMemories() {
      try {
        setLoading(true);
        const data = await api.getMemories();
        setMemories(data);
        setIsDemoMode(false);
      } catch (err) {
        console.warn("API Offline, loading mock memories:", err);
        setMemories(MOCK_MEMORIES);
        setIsDemoMode(true);
      } finally {
        setLoading(false);
      }
    }
    loadMemories();
  }, []);

  const filteredMemories = memories.filter(m => 
    m.memory_text.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (m.brand && m.brand.toLowerCase().includes(searchTerm.toLowerCase())) ||
    (m.style && m.style.toLowerCase().includes(searchTerm.toLowerCase())) ||
    (m.industry && m.industry.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      
      {/* Title block */}
      <div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight">Hindsight Memory Substrate</h1>
        <p className="text-sm text-slate-400 mt-1">Audit the persistent memory nodes generated by campaign results.</p>
      </div>

      {/* Search Bar */}
      <div className="relative w-full bg-slate-900/30 border border-white/5 rounded-xl p-4 glass">
        <Search className="absolute left-7 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
        <input 
          type="text" 
          placeholder="Query memories by keyword, style, brand, or learnings..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full bg-slate-950 border border-white/5 rounded-lg py-2.5 pl-11 pr-4 text-sm text-slate-200 focus:outline-none focus:border-violet-500/50"
        />
      </div>

      {/* Timeline view */}
      <div className="border border-white/5 rounded-2xl bg-slate-900/30 p-6 sm:p-8 glass relative">
        <div className="absolute top-0 right-0 w-32 h-32 bg-violet-600/5 rounded-full blur-[40px] pointer-events-none" />
        
        {loading ? (
          <div className="flex flex-col items-center justify-center py-16 gap-2">
            <div className="w-8 h-8 border-4 border-violet-500/20 border-t-violet-500 rounded-full animate-spin" />
            <span className="text-xs text-slate-400 font-mono">Accessing memory core...</span>
          </div>
        ) : filteredMemories.length === 0 ? (
          <div className="text-center py-12 text-slate-500">
            <Brain className="w-12 h-12 text-slate-700 mx-auto mb-3" />
            <p className="text-sm font-semibold">No memories found.</p>
            <p className="text-xs text-slate-600 mt-1">Submit campaign performance results to write memory nodes.</p>
          </div>
        ) : (
          <div className="relative pl-6 sm:pl-8 border-l border-white/10 space-y-8">
            
            {filteredMemories.map((m, idx) => (
              <div key={m.id} className="relative group">
                
                {/* Timeline node dot indicator */}
                <div className="absolute -left-[31px] sm:-left-[39px] top-1.5 w-4 h-4 rounded-full border border-violet-500/50 bg-[#03040b] flex items-center justify-center group-hover:scale-110 transition-transform">
                  <div className="w-2 h-2 rounded-full bg-violet-400 animate-pulse" />
                </div>
                
                {/* Memory card details */}
                <div className="p-5 rounded-2xl border border-white/5 bg-slate-900/20 group-hover:border-violet-500/20 transition-all">
                  
                  {/* Card Header info */}
                  <div className="flex flex-wrap items-center justify-between gap-3 mb-3">
                    <div className="flex items-center gap-2">
                      {m.brand && (
                        <span className="text-sm font-bold text-white">{m.brand}</span>
                      )}
                      {m.style && (
                        <span className="px-2 py-0.5 rounded bg-slate-800 text-[10px] text-slate-400 font-mono border border-white/5">
                          {m.style}
                        </span>
                      )}
                    </div>
                    
                    <div className="flex items-center gap-1.5 text-[10px] text-slate-500 font-mono">
                      <Clock className="w-3.5 h-3.5" />
                      <span>{new Date(m.created_at).toLocaleString()}</span>
                    </div>
                  </div>
                  
                  {/* Memory text block */}
                  <p className="text-xs sm:text-sm text-slate-300 font-mono leading-relaxed bg-slate-950/45 p-4 rounded-xl border border-white/5 border-l-2 border-l-violet-500 select-all">
                    {m.memory_text}
                  </p>
                  
                  {/* Jump Action footer */}
                  <div className="flex items-center justify-between mt-4 pt-3 border-t border-white/5 text-[11px]">
                    <span className="text-slate-500 font-mono">Node Index: #{m.id} • Campaign Ref: #{m.campaign_id}</span>
                    <Link 
                      href={`/dashboard/campaigns/${m.campaign_id}`}
                      className="font-bold text-violet-400 hover:text-violet-300 flex items-center gap-0.5"
                    >
                      Audit Source Campaign <TrendingUp className="w-3 h-3" />
                    </Link>
                  </div>

                </div>

              </div>
            ))}

          </div>
        )}
      </div>

    </div>
  );
}
